# Generated by Django 2.2.3 on 2019-08-03 06:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import firstapp.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('firstapp', '0002_users'),
    ]

    
