# Generated by Django 2.2.3 on 2019-08-03 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0005_auto_20190803_2326'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
